
function toggleMenu(){document.getElementById('nav').classList.toggle('open')}
function openStripe(url){if(!url||url.includes('REPLACE_')){alert('Stripe Payment Link not added yet.');return}window.location.href=url}
async function getJSON(path){const r=await fetch(path+'?ts='+Date.now());return r.json()}
async function getProducts(){return (await getJSON('/data/products.json')).filter(p=>p.visible!==false && p.status!=='draft')}
async function loadSettings(){try{const s=await getJSON('/data/site.json');document.querySelectorAll('[data-site]').forEach(el=>{const k=el.dataset.site;if(s[k])el.textContent=s[k]});}catch(e){}}
async function loadProducts(limit){const products=await getProducts();const box=document.getElementById('product-grid');if(!box)return;const list=limit?products.filter(p=>p.featured).concat(products.filter(p=>!p.featured)).slice(0,limit):products;box.innerHTML=list.map(p=>`<article class="card"><img src="${p.image||'/assets/hero-products.png'}" alt="${p.name}"><div class="card-body"><p class="eyebrow">${p.category||''}</p><h3>${p.name}</h3><p>${p.short_description||''}</p><p class="price">${p.price||''}</p><p><span class="status">${(p.inventory??0)>0?'In Stock':'Check Availability'}</span></p><a class="btn" href="/product.html?slug=${p.slug}">View Product</a></div></article>`).join('')}
async function loadProduct(){const slug=new URLSearchParams(location.search).get('slug');const products=await getProducts();const p=products.find(x=>x.slug===slug)||products[0];if(!p)return;document.title=p.name+' | Hayti’s';['name','category','short_description','price','ingredients','directions','qr_education','sku','inventory'].forEach(k=>{const el=document.getElementById(k);if(el)el.textContent=p[k]??''});document.getElementById('pimg').src=p.image||'/assets/product-tea.png';document.getElementById('buy').onclick=()=>openStripe(p.stripe_url)}
function newsletterSubmit(e){e.preventDefault();alert('Newsletter integration ready.')} loadSettings();
