
let products=[], editingIndex=null, site={}, imgData="";
const $=s=>document.querySelector(s);
async function load(){try{products=await (await fetch('/data/products.json?ts='+Date.now())).json()}catch{products=[]}try{site=await (await fetch('/data/site.json?ts='+Date.now())).json()}catch{site={}}dashboard()}
function shell(){document.body.innerHTML=`<div class="app"><aside class="side"><div class="logo-row"><img src="/assets/haytis-logo-transparent.png"></div><a href="#" onclick="dashboard()">Dashboard</a><a href="#" onclick="productsView()">Products</a><a href="#" onclick="newProduct()">Add Product</a><a href="#" onclick="settingsView()">Settings</a><a href="/" target="_blank">View Site</a></aside><main class="main" id="main"></main></div>`}
function dashboard(){shell();let active=products.filter(p=>p.visible!==false&&p.status!=='draft').length;let low=products.filter(p=>(Number(p.inventory)||0)<=5).length;$('#main').innerHTML=`<div class="top"><div><h1>Hayti’s Business Platform</h1><p>Shopify-style product manager for your Cloudflare Pages website.</p></div><button onclick="newProduct()">+ Add Product</button></div><div class="cards"><div class="metric">Products<br><strong>${products.length}</strong></div><div class="metric">Active<br><strong>${active}</strong></div><div class="metric">Low Inventory<br><strong>${low}</strong></div><div class="metric">Stripe Links<br><strong>${products.filter(p=>p.stripe_url&&!p.stripe_url.includes('REPLACE_')).length}</strong></div></div><div class="note"><strong>Publish workflow:</strong> Edit products here → Export Products → replace <strong>data/products.json</strong> in GitHub → commit changes. No D1, no Functions, no Cloudflare bindings.</div>`}
function productsView(){shell();$('#main').innerHTML=`<div class="top"><h1>Products</h1><div><button onclick="newProduct()">+ Add Product</button> <button class="secondary" onclick="downloadProducts()">Export Products</button></div></div><div class="panel">${products.map((p,i)=>`<div class="product-row"><img src="${p.image||'/assets/hero-products.png'}"><div><strong>${p.name}</strong><br><small>${p.category||''} • ${p.price||''} • SKU: ${p.sku||''} • Inventory: ${p.inventory??0}</small></div><button onclick="edit(${i})">Edit</button><button class="danger" onclick="del(${i})">Delete</button></div>`).join('')||'<p>No products yet.</p>'}</div>`}
function newProduct(){editingIndex=null;productForm({visible:true,featured:false,status:'active',image:'/assets/hero-products.png',inventory:0})}
function edit(i){editingIndex=i;productForm(products[i])}
function productForm(p){shell();imgData=p.image||'';$('#main').innerHTML=`<div class="top"><h1>${editingIndex===null?'Add Product':'Edit Product'}</h1><button class="secondary" onclick="productsView()">Back</button></div><div class="panel"><div class="form"><label>Product Name<input id="name" value="${esc(p.name)}"></label><label>Slug<input id="slug" value="${esc(p.slug)}"></label><label>Category<input id="category" value="${esc(p.category)}"></label><label>Price<input id="price" value="${esc(p.price)}"></label><label>SKU<input id="sku" value="${esc(p.sku)}"></label><label>Inventory<input id="inventory" type="number" value="${p.inventory??0}"></label><label>Status<select id="status"><option ${p.status==='active'?'selected':''}>active</option><option ${p.status==='draft'?'selected':''}>draft</option><option ${p.status==='sold-out'?'selected':''}>sold-out</option></select></label><label>Visible<select id="visible"><option value="true" ${p.visible!==false?'selected':''}>Yes</option><option value="false" ${p.visible===false?'selected':''}>No</option></select></label><label>Featured<select id="featured"><option value="false" ${!p.featured?'selected':''}>No</option><option value="true" ${p.featured?'selected':''}>Yes</option></select></label><label class="full">Image URL or drag image below<input id="image" value="${esc(p.image)}"></label><div class="full drop" id="drop">Drag & drop product image here<br><small>Image is saved into the exported products.json file.</small><img class="preview" id="preview" src="${p.image||'/assets/hero-products.png'}"></div><label class="full">Short Description<textarea id="short_description">${esc(p.short_description)}</textarea></label><label class="full">Ingredients<textarea id="ingredients">${esc(p.ingredients)}</textarea></label><label class="full">Directions<textarea id="directions">${esc(p.directions)}</textarea></label><label class="full">QR Education<textarea id="qr_education">${esc(p.qr_education)}</textarea></label><label class="full">Stripe Payment Link<input id="stripe_url" value="${esc(p.stripe_url)}"></label><div class="full"><button onclick="saveProduct()">Save Product</button> <button class="secondary" onclick="productsView()">Cancel</button></div></div></div>`;setupDrop()}
function setupDrop(){let d=$('#drop');d.addEventListener('dragover',e=>{e.preventDefault();d.style.borderColor='#f4c04f'});d.addEventListener('dragleave',()=>d.style.borderColor='');d.addEventListener('drop',e=>{e.preventDefault();let f=e.dataTransfer.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{imgData=r.result;$('#image').value=imgData;$('#preview').src=imgData};r.readAsDataURL(f)})}
function getForm(){return {name:v('name'),slug:v('slug')||slugify(v('name')),category:v('category'),price:v('price'),sku:v('sku'),inventory:Number(v('inventory'))||0,status:v('status'),visible:v('visible')==='true',featured:v('featured')==='true',image:v('image')||imgData||'/assets/hero-products.png',short_description:v('short_description'),ingredients:v('ingredients'),directions:v('directions'),qr_education:v('qr_education'),stripe_url:v('stripe_url')}}
function saveProduct(){let p=getForm();if(!p.name){alert('Product name required');return}if(editingIndex===null)products.push(p);else products[editingIndex]=p;editingIndex=null;productsView()}
function del(i){if(confirm('Delete product?')){products.splice(i,1);productsView()}}
function settingsView(){shell();$('#main').innerHTML=`<div class="top"><h1>Site Settings</h1><button onclick="downloadSite()">Export Settings</button></div><div class="panel"><div class="form"><label>Business Name<input id="businessName" value="${esc(site.businessName)}"></label><label>Tagline<input id="tagline" value="${esc(site.tagline)}"></label><label>Email<input id="email" value="${esc(site.email)}"></label><label>Location<input id="location" value="${esc(site.location)}"></label><label class="full">Announcement<textarea id="announcement">${esc(site.announcement)}</textarea></label><label>Newsletter Form Action<input id="newsletterAction" value="${esc(site.newsletterAction)}"></label><label>Google Analytics ID<input id="analyticsId" value="${esc(site.analyticsId)}"></label><label>Meta Pixel ID<input id="metaPixelId" value="${esc(site.metaPixelId)}"></label><div class="full"><button onclick="saveSite()">Save Settings</button></div></div></div>`}
function saveSite(){['businessName','tagline','email','location','announcement','newsletterAction','analyticsId','metaPixelId'].forEach(k=>site[k]=v(k));alert('Settings saved in browser. Export Settings and upload data/site.json to GitHub.')}
function downloadProducts(){download('products.json',JSON.stringify(products,null,2));alert('Upload this file to GitHub at data/products.json, then commit changes.')}
function downloadSite(){download('site.json',JSON.stringify(site,null,2));alert('Upload this file to GitHub at data/site.json, then commit changes.')}
function download(name,text){let b=new Blob([text],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function v(id){return document.getElementById(id).value} function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')} function slugify(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')} load();
